-- exasol-mariadb-compat 8b1f4b4
-- Auto-generated by build.sh from udfs/ and preprocessor/ — DO NOT EDIT.
-- Install:  exaplus -f dist/mariadb-compat.sql
--     or:   python install.py ...
--
-- Import directly into Exasol via an Exasol connector (exaplus, the
-- pyexasol-based install.py, or any Exasol driver) — NOT through MaxScale.
-- The --/ ... / script-block markers and CREATE SCRIPT bodies below are
-- exaplus/Exasol-native and do not survive a MariaDB client + preprocessor.
--
-- exaplus 25.2.6 does not enter script-body mode for CREATE PREPROCESSOR
-- SCRIPT (works fine for SCALAR SCRIPT). The bundle therefore wraps
-- SCALAR UDFs in --/ ... / blocks and emits PREPROCESSOR scripts with
-- a bare trailing `;` — preprocessor source files must keep `;` out of
-- their Python comments so the bare-`;` form has a single statement
-- terminator at the very end.

CREATE SCHEMA IF NOT EXISTS UTIL;

-- === udfs/json/json_extract.sql ===
--/
CREATE OR REPLACE PYTHON3 SCALAR SCRIPT UTIL.JSON_EXTRACT(
    doc   VARCHAR(2000000),
    paths VARCHAR(2000000)
) RETURNS VARCHAR(2000000) AS
import json
import re

# MariaDB JSON_EXTRACT semantics:
#   - one path  -> that match as JSON text (strings quoted, numbers bare,
#                  objects/arrays preserved)
#   - multi     -> JSON array of found values, missing paths silently skipped
#   - all miss  -> NULL
# Path grammar: "$", "$.key", "$[idx]", combinations. Wildcards are not supported;
# unsupported paths behave as "missing" (conservative -- MariaDB would error).
_TOKEN = re.compile(r"\.([A-Za-z_][A-Za-z_0-9]*)|\[(\d+)\]")
_UNSUPPORTED = re.compile(r"\*\*|\[\*\]|\?|\(")
_MISS = object()


def _resolve(node, path):
    if not isinstance(path, str) or not path.startswith("$"):
        return _MISS
    rest = path[1:]
    if _UNSUPPORTED.search(rest):
        return _MISS
    i = 0
    cur = node
    while i < len(rest):
        m = _TOKEN.match(rest, i)
        if not m:
            return _MISS
        key, idx = m.groups()
        if key is not None:
            if not isinstance(cur, dict) or key not in cur:
                return _MISS
            cur = cur[key]
        else:
            j = int(idx)
            if not isinstance(cur, list) or j >= len(cur):
                return _MISS
            cur = cur[j]
        i = m.end()
    return cur


def run(ctx):
    if ctx.doc is None or ctx.paths is None:
        return None
    try:
        data = json.loads(ctx.doc)
    except (ValueError, TypeError):
        return None
    try:
        path_list = json.loads(ctx.paths)
    except (ValueError, TypeError):
        return None
    if not isinstance(path_list, list):
        path_list = [path_list]
    found = []
    for p in path_list:
        v = _resolve(data, p)
        if v is not _MISS:
            found.append(v)
    if not found:
        return None
    if len(path_list) == 1:
        return json.dumps(found[0])
    return json.dumps(found)
/

-- === udfs/json/json_merge_preserve.sql ===
--/
CREATE OR REPLACE PYTHON3 SCALAR SCRIPT UTIL.JSON_MERGE_PRESERVE(...)
RETURNS VARCHAR(2000000) AS

import json

# MariaDB JSON_MERGE_PRESERVE semantics:
#   - Requires >= 2 args.
#   - Any NULL arg -> NULL.
#   - Adjacent objects: union by key; if a key collides, values are combined
#     (recursively merged: two objects -> nested merge; everything else -> autowrap
#     each side to an array and concatenate).
#   - Adjacent arrays: concatenate.
#   - Mixed object/array or scalars: autowrap each side to an array and concatenate.
# JSON_MERGE is a deprecated MariaDB alias and shares the same semantics; the
# preprocessor maps both names to this UDF.
# Invalid JSON in any arg -> NULL (MariaDB raises; we return NULL conservatively
# rather than aborting the whole statement).

_MISS = object()


def _parse(s):
    try:
        return json.loads(s)
    except (ValueError, TypeError):
        return _MISS


def _merge(a, b):
    if isinstance(a, dict) and isinstance(b, dict):
        out = dict(a)
        for k, v in b.items():
            out[k] = _merge(out[k], v) if k in out else v
        return out
    if isinstance(a, list) and isinstance(b, list):
        return a + b
    a_list = a if isinstance(a, list) else [a]
    b_list = b if isinstance(b, list) else [b]
    return a_list + b_list


def run(ctx):
    n = exa.meta.input_column_count
    if n < 2:
        raise ValueError('JSON_MERGE_PRESERVE requires at least 2 arguments')
    vals = []
    for i in range(n):
        s = ctx[i]
        if s is None:
            return None
        v = _parse(s)
        if v is _MISS:
            return None
        vals.append(v)
    result = vals[0]
    for nxt in vals[1:]:
        result = _merge(result, nxt)
    return json.dumps(result, ensure_ascii=False)
/

-- === udfs/json/json_object.sql ===
--/
CREATE OR REPLACE PYTHON3 SCALAR SCRIPT UTIL.JSON_OBJECT(...)
RETURNS VARCHAR(2000000) AS

import json
import decimal
import datetime


def default_serializer(obj):
    if isinstance(obj, decimal.Decimal):
        if obj == obj.to_integral_value():
            return int(obj)
        return float(obj)
    if isinstance(obj, datetime.datetime):
        return obj.isoformat()
    if isinstance(obj, datetime.date):
        return obj.isoformat()
    raise TypeError(f'Object of type {type(obj).__name__} is not JSON serializable')


def run(ctx):
    n = exa.meta.input_column_count
    if n % 2 != 0:
        raise ValueError('JSON_OBJECT requires an even number of arguments (key-value pairs)')
    obj = {}
    for i in range(0, n, 2):
        key = ctx[i]
        if key is None:
            raise ValueError('JSON_OBJECT key must not be NULL')
        key = str(key)
        value = ctx[i + 1]
        # If a value is a string that looks like a JSON container (object or
        # array), parse it and embed the parsed value. Without this, a nested
        # UTIL.JSON_OBJECT (or JSON_EXTRACT / JSON_MERGE_PRESERVE) returns
        # JSON text that the outer call would re-quote as a string, producing
        # escaped output instead of properly nested JSON. Bare literals like
        # 'true' / 'null' / '123' are NOT parsed — that would change the
        # meaning of user-supplied scalar strings. A caller who genuinely
        # supplies a string that opens with '{' or '[' and happens to be valid
        # JSON will see it interpreted as JSON; this matches the behavior of
        # MariaDB's implicit JSON typing.
        if isinstance(value, str) and value[:1] in ('{', '['):
            try:
                value = json.loads(value)
            except ValueError:
                pass
        obj[key] = value
    return json.dumps(obj, default=default_serializer, ensure_ascii=False)
/

-- === udfs/json/json_objectagg.sql ===
--/
CREATE OR REPLACE PYTHON3 SCALAR SCRIPT UTIL.JSON_OBJECTAGG(s VARCHAR(2000000))
RETURNS VARCHAR(2000000) AS

import json


# MariaDB JSON_OBJECTAGG(key, value) aggregates rows into a single JSON object.
# Exasol implements user-defined aggregates as SET SCRIPTs, but emitting SET
# SCRIPTs cannot appear inside any expression context (scalar subqueries,
# argument positions, CTE referenced from an outer expression — all rejected
# with "emitting function in expression"). MariaDB JSON_OBJECTAGG routinely
# appears inside JSON_OBJECT(...) or as a scalar subquery, so a SET SCRIPT
# wouldn't cover real workloads.
#
# Workaround: the preprocessor rewrites MariaDB-form JSON_OBJECTAGG(k, v) into
#   UTIL.JSON_OBJECTAGG(LISTAGG(UTIL.JSON_OBJECT(k, v), ','))
# LISTAGG is a standard SQL aggregate (expression-safe). It concatenates each
# row's mini JSON object — produced by UTIL.JSON_OBJECT, which handles type
# coercion, JSON nesting, and NULL-key errors — into one comma-joined string.
# This UDF then wraps that string in [...] to make a JSON array, parses, and
# merges the per-row objects into one.
#
# Semantics:
#   - Empty group -> LISTAGG returns NULL -> we return NULL. Matches MariaDB.
#   - NULL key -> UTIL.JSON_OBJECT raises -> error propagates. Matches MariaDB.
#   - NULL value -> embedded as JSON `null`. Matches MariaDB.
#   - Duplicate keys -> last-write-wins (`dict.update`). Matches MariaDB's
#     "rows processed in unspecified order, later one wins" behavior.
#   - Aggregation order is whatever LISTAGG produces (no WITHIN GROUP ORDER BY
#     added by the preprocessor, so unspecified); same as MariaDB.


def run(ctx):
    s = ctx[0]
    if s is None:
        return None
    arr = json.loads('[' + s + ']')
    out = {}
    for o in arr:
        out.update(o)
    return json.dumps(out, ensure_ascii=False)
/

-- === udfs/json/json_quote.sql ===
--/
CREATE OR REPLACE PYTHON3 SCALAR SCRIPT UTIL.JSON_QUOTE(
    val VARCHAR(2000000)
) RETURNS VARCHAR(2000000) AS
import json

# MariaDB JSON_QUOTE semantics: wrap the argument as a JSON string literal,
# escaping interior quotes and control characters.
#   NULL          -> NULL
#   'hello'       -> '"hello"'
#   'a"b'         -> '"a\"b"'           (interior " escaped)
#   'a' + LF +'b' -> '"a\nb"'           (control chars escaped)
#   'null'        -> '"null"'           (no JSON parsing; always a string)
# Inverse of UTIL.JSON_UNQUOTE for string inputs.
#
# Exasol quirk: VARCHAR '' is indistinguishable from NULL at the UDF boundary
# (Exasol treats '' IS NULL as TRUE), so JSON_QUOTE('') returns NULL on Exasol
# even though MariaDB returns '""'. This is a platform-level limitation, not a
# UDF bug — the run() body would otherwise produce '""' on a literal ''.


def run(ctx):
    s = ctx.val
    if s is None:
        return None
    return json.dumps(s)
/

-- === udfs/json/json_unquote.sql ===
--/
CREATE OR REPLACE PYTHON3 SCALAR SCRIPT UTIL.JSON_UNQUOTE(
    val VARCHAR(2000000)
) RETURNS VARCHAR(2000000) AS
import json

# MariaDB JSON_UNQUOTE semantics (lenient variant; MySQL is stricter):
#   NULL                 -> NULL
#   '"hello"'            -> 'hello'             (JSON string -> unescaped text)
#   '"a\\nb"'            -> 'a' + LF + 'b'      (JSON escapes resolved)
#   anything else        -> input unchanged     (numbers, objects, arrays,
#                                                already-unquoted text, garbage)
# A value counts as a JSON string only if it parses to a Python str. Objects
# and arrays pass through verbatim, matching MariaDB's behavior.


def run(ctx):
    s = ctx.val
    if s is None:
        return None
    if len(s) >= 2 and s[0] == '"' and s[-1] == '"':
        try:
            v = json.loads(s)
        except ValueError:
            return s
        if isinstance(v, str):
            return v
    return s
/

-- === udfs/meta/get_glot_version.sql ===
--/
CREATE OR REPLACE PYTHON3 SCALAR SCRIPT UTIL.GET_GLOT_VERSION()
RETURNS VARCHAR(64) AS

# Returns the sqlglot version string visible to the active SCRIPT_LANGUAGES
# SLC. Lets tests confirm they're hitting the SLC they expect — some preprocessor
# rewrites (e.g. USE -> OPEN SCHEMA from sqlglot PR #7538) only work on SLCs
# whose bundled sqlglot is recent enough.

import sqlglot


def run(ctx):
    return getattr(sqlglot, "__version__", "unknown")
/

-- === udfs/string/elt.sql ===
--/
CREATE OR REPLACE PYTHON3 SCALAR SCRIPT UTIL.ELT(...)
RETURNS VARCHAR(2000000) AS

# MariaDB ELT(N, str1[, str2, ...]) semantics:
#   - 1-based pick: ELT(1, 'a', 'b', 'c') -> 'a', ELT(2, ...) -> 'b'.
#   - N is NULL          -> NULL.
#   - N < 1 or N > count -> NULL.
#   - Selected element itself NULL -> NULL.
#   - Fractional N is truncated toward zero (ELT(2.7, 'a', 'b', 'c') -> 'b').
#   - Non-numeric N (e.g. an arbitrary string) -> NULL conservatively.
# Requires at least 2 args (one index + one string); fewer raises (matches MariaDB syntax).


def run(ctx):
    n_args = exa.meta.input_column_count
    if n_args < 2:
        raise ValueError('ELT requires at least 2 arguments (index and one string)')
    raw = ctx[0]
    if raw is None:
        return None
    try:
        n = int(float(raw))
    except (ValueError, TypeError):
        return None
    string_count = n_args - 1
    if n < 1 or n > string_count:
        return None
    val = ctx[n]
    return None if val is None else str(val)
/

-- === udfs/string/field.sql ===
--/
CREATE OR REPLACE PYTHON3 SCALAR SCRIPT UTIL.FIELD(...)
RETURNS INT AS

# MariaDB FIELD(str, str1[, str2, ...]) semantics:
#   - 1-based search: returns the index of `str` in the list, or 0 if not found.
#   - str is NULL          -> 0 (NULL never equals NULL, so it's never "found").
#   - List element NULL    -> skipped, never matches.
#   - All args numeric     -> numeric comparison.
#   - Otherwise            -> case-sensitive string comparison. MariaDB's
#     "convert mixed args to double" rule is intentionally NOT replicated:
#     it silently coerces non-numeric strings to 0 and produces surprising
#     matches (e.g. FIELD('x', 0, 'y') -> 1). String compare is safer here.
#   - Only `str` provided (no list) -> 0.
# FIELD is the complement of ELT.

import decimal


def run(ctx):
    n_args = exa.meta.input_column_count
    if n_args < 1:
        raise ValueError('FIELD requires at least 1 argument (the search value)')
    needle = ctx[0]
    if needle is None:
        return 0
    if n_args == 1:
        return 0

    vals = [ctx[i] for i in range(1, n_args)]

    numeric = (isinstance(needle, (int, float, decimal.Decimal))
               and all(v is None or isinstance(v, (int, float, decimal.Decimal))
                       for v in vals))

    if numeric:
        n = float(needle)
        for i, v in enumerate(vals, start=1):
            if v is None:
                continue
            if float(v) == n:
                return i
        return 0

    s = str(needle)
    for i, v in enumerate(vals, start=1):
        if v is None:
            continue
        if str(v) == s:
            return i
    return 0
/

-- === preprocessor/maria_preprocessor.sql ===
CREATE OR REPLACE PYTHON3 PREPROCESSOR SCRIPT UTIL.MARIA_PREPROCESSOR AS

import json
import sqlglot
from sqlglot import expressions as exp


_PREPROCESSOR_VERSION = "2026.6.0"
_PREPROCESSOR_BUILD = "8b1f4b4"


def adapter_call(request):
    try:
        return _transpile(request)
    except Exception:
        return request


_SYSVAR_VALUES = {
    "max_allowed_packet": "16777216",
    "auto_increment_increment": "1",
    "system_time_zone": "UTC",
    "time_zone": "+00:00",
}


def _rewrite_session_var_select(tree):
    if not isinstance(tree, exp.Select):
        return None
    projs = tree.expressions
    if not projs or not all(isinstance(e, exp.SessionParameter) for e in projs):
        return None
    if len(projs) == 1 and projs[0].sql(dialect="mysql").lstrip("@").lower() == "maria_preprocessor_version":
        ver = _PREPROCESSOR_VERSION + "_" + _PREPROCESSOR_BUILD
        return "SELECT '" + ver.replace("'", "''") + "'"
    cols = []
    for sp in projs:
        key = sp.sql(dialect="mysql").lstrip("@").lower()
        val = _SYSVAR_VALUES.get(key)
        if val is None:
            cols.append("NULL")
        elif val.isdigit():
            cols.append(val)
        else:
            cols.append("'" + val.replace("'", "''") + "'")
    return "SELECT " + ", ".join(cols)


def _transpile(request):
    tree = sqlglot.parse_one(request, read="mysql")
    if tree is None:
        return request
    sysvars = _rewrite_session_var_select(tree)
    if sysvars is not None:
        return sysvars
    tree = tree.transform(_rewrite_to_util)
    return tree.sql(dialect="exasol", identify=True)


def _rewrite_to_util(node):
    if (isinstance(node, exp.Column)
            and node.table == ""
            and node.name
            and node.name.upper() in _EXASOL_BARE_KEYWORDS):
        return exp.Var(this=node.name)

    if isinstance(node, exp.Set):
        items = node.expressions or []
        if items and all(
                isinstance(it, exp.SetItem)
                and (it.args.get("kind") in ("NAMES", "CHARACTER SET")
                     or isinstance(it.this, exp.EQ))
                for it in items):
            return exp.Command(
                this="--",
                expression=exp.Literal.string(
                    " mariadb session SET is a no-op on Exasol"),
            )

    if isinstance(node, exp.CTE):
        inner = node.this
        if isinstance(inner, exp.Select):
            _alias_unaliased_select(inner)
        elif isinstance(inner, exp.Union):
            for sub in inner.find_all(exp.Select):
                _alias_unaliased_select(sub)
        return node

    if isinstance(node, exp.JSONExtract) and not node.args.get("emits"):
        paths = []
        if node.expression is not None:
            paths.append(_strip_sql_quotes(node.expression.sql()))
        paths.extend(_strip_sql_quotes(p.sql()) for p in node.expressions)
        return exp.Anonymous(
            this="UTIL.JSON_EXTRACT",
            expressions=[node.this, exp.Literal.string(json.dumps(paths))],
        )

    if isinstance(node, exp.JSONObject):
        args = []
        for kv in node.expressions:
            k = kv.this
            v = kv.expression
            if isinstance(k, exp.Expression):
                k = k.transform(_rewrite_to_util)
            if isinstance(v, exp.Expression):
                v = v.transform(_rewrite_to_util)
            args.append(k)
            args.append(v)
        return exp.Anonymous(this="UTIL.JSON_OBJECT", expressions=args)

    if (isinstance(node, exp.Anonymous)
            and isinstance(node.this, str)
            and node.this.upper() == "JSON_OBJECTAGG"):
        new_exprs = [e.transform(_rewrite_to_util) if isinstance(e, exp.Expression) else e
                     for e in node.expressions]
        return _wrap_json_objectagg(new_exprs)

    _JSONObjectAgg = getattr(exp, "JSONObjectAgg", None)
    if _JSONObjectAgg is not None and isinstance(node, _JSONObjectAgg):
        args = []
        for kv in node.expressions:
            k = kv.this
            v = kv.expression
            if isinstance(k, exp.Expression):
                k = k.transform(_rewrite_to_util)
            if isinstance(v, exp.Expression):
                v = v.transform(_rewrite_to_util)
            args.append(k)
            args.append(v)
        return _wrap_json_objectagg(args)

    if (isinstance(node, exp.Anonymous)
            and isinstance(node.this, str)
            and node.this.upper() == "JSON_UNQUOTE"):
        new_exprs = [e.transform(_rewrite_to_util) if isinstance(e, exp.Expression) else e
                     for e in node.expressions]
        return exp.Anonymous(this="UTIL.JSON_UNQUOTE", expressions=new_exprs)

    if (isinstance(node, exp.Anonymous)
            and isinstance(node.this, str)
            and node.this.upper() == "JSON_QUOTE"):
        new_exprs = [e.transform(_rewrite_to_util) if isinstance(e, exp.Expression) else e
                     for e in node.expressions]
        return exp.Anonymous(this="UTIL.JSON_QUOTE", expressions=new_exprs)

    if (isinstance(node, exp.Anonymous)
            and isinstance(node.this, str)
            and node.this.upper() in ("JSON_MERGE_PRESERVE", "JSON_MERGE")):
        new_exprs = [e.transform(_rewrite_to_util) if isinstance(e, exp.Expression) else e
                     for e in node.expressions]
        return exp.Anonymous(this="UTIL.JSON_MERGE_PRESERVE", expressions=new_exprs)

    if (isinstance(node, exp.Anonymous)
            and isinstance(node.this, str)
            and node.this.upper() == "ELT"):
        new_exprs = [e.transform(_rewrite_to_util) if isinstance(e, exp.Expression) else e
                     for e in node.expressions]
        return exp.Anonymous(this="UTIL.ELT", expressions=new_exprs)

    _Elt = getattr(exp, "Elt", None)
    if _Elt is not None and isinstance(node, _Elt):
        args = [node.this, *node.expressions]
        new_args = [a.transform(_rewrite_to_util) if isinstance(a, exp.Expression) else a
                    for a in args]
        return exp.Anonymous(this="UTIL.ELT", expressions=new_args)

    if (isinstance(node, exp.Anonymous)
            and isinstance(node.this, str)
            and node.this.upper() == "FIELD"):
        new_exprs = [e.transform(_rewrite_to_util) if isinstance(e, exp.Expression) else e
                     for e in node.expressions]
        return exp.Anonymous(this="UTIL.FIELD", expressions=new_exprs)

    return node


def _wrap_json_objectagg(args):
    if len(args) == 2:
        per_row = exp.Anonymous(this="UTIL.JSON_OBJECT", expressions=list(args))
        listagg = exp.Anonymous(
            this="LISTAGG",
            expressions=[per_row, exp.Literal.string(",")],
        )
        return exp.Anonymous(this="UTIL.JSON_OBJECTAGG", expressions=[listagg])
    return exp.Anonymous(this="UTIL.JSON_OBJECTAGG", expressions=args)


def _strip_sql_quotes(rendered):
    if len(rendered) >= 2 and rendered[0] == "'" and rendered[-1] == "'":
        return rendered[1:-1].replace("''", "'")
    return rendered


_EXASOL_BARE_KEYWORDS = frozenset({
    "CURRENT_SESSION",
    "CURRENT_STATEMENT",
    "CURRENT_SCHEMA",
})


def _alias_unaliased_select(select):
    new_projs = []
    for i, proj in enumerate(select.expressions):
        if isinstance(proj, (exp.Alias, exp.Column, exp.Star)):
            new_projs.append(proj)
        else:
            new_projs.append(exp.alias_(proj, f"_col{i}"))
    select.set("expressions", new_projs)
;

-- === preprocessor/maria_preprocessor_debug.sql ===
CREATE OR REPLACE PYTHON3 PREPROCESSOR SCRIPT UTIL.MARIA_PREPROCESSOR_DEBUG AS


import json
import sqlglot
from sqlglot import expressions as exp


_PREPROCESSOR_VERSION = "2026.6.0"
_PREPROCESSOR_BUILD = "8b1f4b4"


def adapter_call(request):
    return _transpile(request)


_SYSVAR_VALUES = {
    "max_allowed_packet": "16777216",
    "auto_increment_increment": "1",
    "system_time_zone": "UTC",
    "time_zone": "+00:00",
}


def _rewrite_session_var_select(tree):
    if not isinstance(tree, exp.Select):
        return None
    projs = tree.expressions
    if not projs or not all(isinstance(e, exp.SessionParameter) for e in projs):
        return None
    if len(projs) == 1 and projs[0].sql(dialect="mysql").lstrip("@").lower() == "maria_preprocessor_version":
        ver = _PREPROCESSOR_VERSION + "_" + _PREPROCESSOR_BUILD
        return "SELECT '" + ver.replace("'", "''") + "'"
    cols = []
    for sp in projs:
        key = sp.sql(dialect="mysql").lstrip("@").lower()
        val = _SYSVAR_VALUES.get(key)
        if val is None:
            cols.append("NULL")
        elif val.isdigit():
            cols.append(val)
        else:
            cols.append("'" + val.replace("'", "''") + "'")
    return "SELECT " + ", ".join(cols)


def _transpile(request):
    tree = sqlglot.parse_one(request, read="mysql")
    if tree is None:
        return request
    sysvars = _rewrite_session_var_select(tree)
    if sysvars is not None:
        return sysvars
    tree = tree.transform(_rewrite_to_util)
    return tree.sql(dialect="exasol", identify=True)


def _rewrite_to_util(node):
    if (isinstance(node, exp.Column)
            and node.table == ""
            and node.name
            and node.name.upper() in _EXASOL_BARE_KEYWORDS):
        return exp.Var(this=node.name)

    if isinstance(node, exp.Set):
        items = node.expressions or []
        if items and all(
                isinstance(it, exp.SetItem)
                and (it.args.get("kind") in ("NAMES", "CHARACTER SET")
                     or isinstance(it.this, exp.EQ))
                for it in items):
            return exp.Command(
                this="--",
                expression=exp.Literal.string(
                    " mariadb session SET is a no-op on Exasol"),
            )

    if isinstance(node, exp.CTE):
        inner = node.this
        if isinstance(inner, exp.Select):
            _alias_unaliased_select(inner)
        elif isinstance(inner, exp.Union):
            for sub in inner.find_all(exp.Select):
                _alias_unaliased_select(sub)
        return node

    if isinstance(node, exp.JSONExtract) and not node.args.get("emits"):
        paths = []
        if node.expression is not None:
            paths.append(_strip_sql_quotes(node.expression.sql()))
        paths.extend(_strip_sql_quotes(p.sql()) for p in node.expressions)
        return exp.Anonymous(
            this="UTIL.JSON_EXTRACT",
            expressions=[node.this, exp.Literal.string(json.dumps(paths))],
        )

    if isinstance(node, exp.JSONObject):
        args = []
        for kv in node.expressions:
            k = kv.this
            v = kv.expression
            if isinstance(k, exp.Expression):
                k = k.transform(_rewrite_to_util)
            if isinstance(v, exp.Expression):
                v = v.transform(_rewrite_to_util)
            args.append(k)
            args.append(v)
        return exp.Anonymous(this="UTIL.JSON_OBJECT", expressions=args)

    if (isinstance(node, exp.Anonymous)
            and isinstance(node.this, str)
            and node.this.upper() == "JSON_OBJECTAGG"):
        new_exprs = [e.transform(_rewrite_to_util) if isinstance(e, exp.Expression) else e
                     for e in node.expressions]
        return _wrap_json_objectagg(new_exprs)

    _JSONObjectAgg = getattr(exp, "JSONObjectAgg", None)
    if _JSONObjectAgg is not None and isinstance(node, _JSONObjectAgg):
        args = []
        for kv in node.expressions:
            k = kv.this
            v = kv.expression
            if isinstance(k, exp.Expression):
                k = k.transform(_rewrite_to_util)
            if isinstance(v, exp.Expression):
                v = v.transform(_rewrite_to_util)
            args.append(k)
            args.append(v)
        return _wrap_json_objectagg(args)

    if (isinstance(node, exp.Anonymous)
            and isinstance(node.this, str)
            and node.this.upper() == "JSON_UNQUOTE"):
        new_exprs = [e.transform(_rewrite_to_util) if isinstance(e, exp.Expression) else e
                     for e in node.expressions]
        return exp.Anonymous(this="UTIL.JSON_UNQUOTE", expressions=new_exprs)

    if (isinstance(node, exp.Anonymous)
            and isinstance(node.this, str)
            and node.this.upper() == "JSON_QUOTE"):
        new_exprs = [e.transform(_rewrite_to_util) if isinstance(e, exp.Expression) else e
                     for e in node.expressions]
        return exp.Anonymous(this="UTIL.JSON_QUOTE", expressions=new_exprs)

    if (isinstance(node, exp.Anonymous)
            and isinstance(node.this, str)
            and node.this.upper() in ("JSON_MERGE_PRESERVE", "JSON_MERGE")):
        new_exprs = [e.transform(_rewrite_to_util) if isinstance(e, exp.Expression) else e
                     for e in node.expressions]
        return exp.Anonymous(this="UTIL.JSON_MERGE_PRESERVE", expressions=new_exprs)

    if (isinstance(node, exp.Anonymous)
            and isinstance(node.this, str)
            and node.this.upper() == "ELT"):
        new_exprs = [e.transform(_rewrite_to_util) if isinstance(e, exp.Expression) else e
                     for e in node.expressions]
        return exp.Anonymous(this="UTIL.ELT", expressions=new_exprs)

    _Elt = getattr(exp, "Elt", None)
    if _Elt is not None and isinstance(node, _Elt):
        args = [node.this, *node.expressions]
        new_args = [a.transform(_rewrite_to_util) if isinstance(a, exp.Expression) else a
                    for a in args]
        return exp.Anonymous(this="UTIL.ELT", expressions=new_args)

    if (isinstance(node, exp.Anonymous)
            and isinstance(node.this, str)
            and node.this.upper() == "FIELD"):
        new_exprs = [e.transform(_rewrite_to_util) if isinstance(e, exp.Expression) else e
                     for e in node.expressions]
        return exp.Anonymous(this="UTIL.FIELD", expressions=new_exprs)

    return node


def _wrap_json_objectagg(args):
    if len(args) == 2:
        per_row = exp.Anonymous(this="UTIL.JSON_OBJECT", expressions=list(args))
        listagg = exp.Anonymous(
            this="LISTAGG",
            expressions=[per_row, exp.Literal.string(",")],
        )
        return exp.Anonymous(this="UTIL.JSON_OBJECTAGG", expressions=[listagg])
    return exp.Anonymous(this="UTIL.JSON_OBJECTAGG", expressions=args)


def _strip_sql_quotes(rendered):
    if len(rendered) >= 2 and rendered[0] == "'" and rendered[-1] == "'":
        return rendered[1:-1].replace("''", "'")
    return rendered


_EXASOL_BARE_KEYWORDS = frozenset({
    "CURRENT_SESSION",
    "CURRENT_STATEMENT",
    "CURRENT_SCHEMA",
})


def _alias_unaliased_select(select):
    new_projs = []
    for i, proj in enumerate(select.expressions):
        if isinstance(proj, (exp.Alias, exp.Column, exp.Star)):
            new_projs.append(proj)
        else:
            new_projs.append(exp.alias_(proj, f"_col{i}"))
    select.set("expressions", new_projs)
;

